


#          __                _ __  __       
#   ____ _/ /___ ___________(_) /_/ /___  __
#  / __ `/ / __ `/ ___/ ___/ / __/ __/ / / /
# / /_/ / / /_/ / /__/ /  / / /_/ /_/ /_/ / 
# \__,_/_/\__,_/\___/_/  /_/\__/\__/\__, /  
#                                  /____/   


[window]
decorations = "None"

[font]
normal.family = "UbuntuMono Nerd Font"
size = 11

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
